name: first_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -name: print_greeting
      -run: echo "hello world!"
      -name: print_goodbye
      -run: echo "Done-bye!"
      
